# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2018 MediaTek Inc.
#

ccflags-y += -I$(srctree)/drivers/media/platform/mediatek/isp/isp_7x/mtk-hcp
ccflags-y += -I$(srctree)/drivers/media/platform/mediatek/isp/isp_7x/imgsys

obj-$(CONFIG_VIDEO_MTK_ISP_71_IMGSYS) += mtk-ipesys-me.o
