/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018 MediaTek Inc.
 *
 * Author: Daniel Huang <daniel.huang@mediatek.com>
 *
 */

#ifndef _MTK_IMGSYS_CMDQ_PLAT_H_
#define _MTK_IMGSYS_CMDQ_PLAT_H_

#include "mtk_imgsys-cmdq.h"

#define IMGSYS_DVFS_ENABLE     (1)

/* Record info definitions */
#define GCE_REC_MAX_FRAME_BLOCK     (40)
#define GCE_REC_MAX_TILE_BLOCK      (40)
#define GCE_REC_MAX_LABEL_COUNT     (2048)

#define IMGSYS_ENG_MAX 10
#define IMGSYS_REG_START	0x15000000
#define IMGSYS_REG_END		0x1570FFFF

#define IMGSYS_CMD_MAX_SZ_N	0x9000
#define IMGSYS_CMD_MAX_SZ_V	0x50000

#define IMGSYS_NOR_THD 10
#define IMGSYS_MAX_FPS 60

#define IMGSYS_VSS_FREQ_FLOOR	660000000
#define IMGSYS_SMVR_FREQ_FLOOR	393000000

#define IMGSYS_CMDQ_HW_EVENT_BEGIN	0
#define IMGSYS_CMDQ_HW_EVENT_END	(IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_START - 1)
#define IMGSYS_CMDQ_SW_EVENT_BEGIN	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_START
#define IMGSYS_CMDQ_SW_EVENT_END	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_END

#define IMGSYS_CMDQ_GPR_EVENT_BEGIN	999
#define IMGSYS_CMDQ_GPR_EVENT_END	1008
#define IMGSYS_CMDQ_SYNC_POOL_NUM	60

#define WPE_SMI_PORT_NUM	8
#define ME_SMI_PORT_NUM	2
#define PQ_DIP_SMI_PORT_NUM	6
#define TRAW_SMI_PORT_NUM	18
#define LTRAW_SMI_PORT_NUM	7
#define XTRAW_SMI_PORT_NUM	16
#define DIP_SMI_PORT_NUM	39
#define DIP0_SMI_PORT_NUM	20
#define DIP1_SMI_PORT_NUM	19
#define ADL_SMI_PORT_NUM	2

enum mtk_imgsys_event {
	/* HW event */
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_0 = 0,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_1,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_2,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_3,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_4,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_5,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_6,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_7,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_8,
	IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_9,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_0,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_1,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_2,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_3,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_4,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_5,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_6,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_7,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_8,
	IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_9,
	IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_0,
	IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_1,
	IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_2,
	IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_3,
	IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_4,
	IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_5,
	IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_6,
	IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_7,
	IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_8,
	IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_9,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_6,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_7,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_8,
	IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_9,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_6,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_7,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_8,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_9,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_6,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_7,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_8,
	IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_9,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_6,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_7,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_8,
	IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_9,
	IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_6,
	IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_7,
	IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_8,
	IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_9,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_0,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_1,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_2,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_3,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_4,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_5,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_6,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_7,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_8,
	IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_9,
	IMGSYS_CMDQ_EVENT_IMG_IMGSYS_IPE_ME_DONE,
	IMGSYS_CMDQ_EVENT_IMG_ADL_TILE_DONE_EVENT,
	/* SW event */
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_START,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_WPE_EIS = IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_START,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_WPE_TNR,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_WPE_LITE,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_TRAW,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_LTRAW,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_XTRAW,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_DIP,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_PQDIP_A,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_PQDIP_B,
	IMGSYS_CMDQ_SYNC_TOKEN_IPESYS_ME,
	IMGSYS_CMDQ_SYNC_TOKEN_APUSYS_APU,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_TRAW,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_LTRAW,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_XTRAW,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_DIP,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_START,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_1 = IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_START,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_2,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_3,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_4,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_5,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_6,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_7,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_8,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_9,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_10,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_11,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_12,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_13,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_14,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_15,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_16,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_17,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_18,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_19,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_20,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_21,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_22,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_23,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_24,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_25,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_26,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_27,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_28,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_29,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_30,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_31,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_32,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_33,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_34,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_35,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_36,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_37,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_38,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_39,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_40,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_41,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_42,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_43,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_44,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_45,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_46,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_47,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_48,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_49,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_50,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_51,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_52,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_53,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_54,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_55,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_56,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_57,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_58,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_59,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_60,
	IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_END = IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_60,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_1,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_2,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_3,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_4,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_5,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_6,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_7,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_8,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_9,
	IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_10,
	IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ISP_WAIT,
	IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ISP_SET,
	IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ADL_WAIT,
	IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ADL_SET,
	IMGSYS_CMDQ_EVENT_MAX
};

static struct imgsys_event_table imgsys_event[] = {
	/*TRAW frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_0, "traw_cq_thread0_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_1, "traw_cq_thread1_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_2, "traw_cq_thread2_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_3, "traw_cq_thread3_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_4, "traw_cq_thread4_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_5, "traw_cq_thread5_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_6, "traw_cq_thread6_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_7, "traw_cq_thread7_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_8, "traw_cq_thread8_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW0_CQ_THR_DONE_TRAW0_9, "traw_cq_thread9_frame_done"},
	/*LTRAW frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_0, "ltraw_cq_thread0_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_1, "ltraw_cq_thread1_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_2, "ltraw_cq_thread2_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_3, "ltraw_cq_thread3_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_4, "ltraw_cq_thread4_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_5, "ltraw_cq_thread5_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_6, "ltraw_cq_thread6_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_7, "ltraw_cq_thread7_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_8, "ltraw_cq_thread8_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_TRAW1_CQ_THR_DONE_TRAW0_9, "ltraw_cq_thread9_frame_done"},
	/*XTRAW frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_0, "xtraw_cq_thread0_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_1, "xtraw_cq_thread1_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_2, "xtraw_cq_thread2_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_3, "xtraw_cq_thread3_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_4, "xtraw_cq_thread4_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_5, "xtraw_cq_thread5_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_6, "xtraw_cq_thread6_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_7, "xtraw_cq_thread7_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_8, "xtraw_cq_thread8_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_XTRAW_CQ_THR_DONE_TRAW0_9, "xtraw_cq_thread9_frame_done"},
	/*DIP frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_0, "dip_cq_thread0_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_1, "dip_cq_thread1_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_2, "dip_cq_thread2_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_3, "dip_cq_thread3_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_4, "dip_cq_thread4_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_5, "dip_cq_thread5_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_6, "dip_cq_thread6_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_7, "dip_cq_thread7_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_8, "dip_cq_thread8_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_DIP_CQ_THR_DONE_P2_9, "dip_cq_thread9_frame_done"},
	/*PQ_DIP_A frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_0, "pqa_cq_thread0_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_1, "pqa_cq_thread1_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_2, "pqa_cq_thread2_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_3, "pqa_cq_thread3_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_4, "pqa_cq_thread4_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_5, "pqa_cq_thread5_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_6, "pqa_cq_thread6_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_7, "pqa_cq_thread7_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_8, "pqa_cq_thread8_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_A_CQ_THR_DONE_P2_9, "pqa_cq_thread9_frame_done"},
	/*PQ_DIP_B frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_0, "pqb_cq_thread0_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_1, "pqb_cq_thread1_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_2, "pqb_cq_thread2_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_3, "pqb_cq_thread3_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_4, "pqb_cq_thread4_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_5, "pqb_cq_thread5_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_6, "pqb_cq_thread6_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_7, "pqb_cq_thread7_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_8, "pqb_cq_thread8_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_PQDIP_B_CQ_THR_DONE_P2_9, "pqb_cq_thread9_frame_done"},
	/*WPE_EIS frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_0, "wpe_eis_cq_thread0_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_1, "wpe_eis_cq_thread1_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_2, "wpe_eis_cq_thread2_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_3, "wpe_eis_cq_thread3_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_4, "wpe_eis_cq_thread4_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_5, "wpe_eis_cq_thread5_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_6, "wpe_eis_cq_thread6_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_7, "wpe_eis_cq_thread7_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_8, "wpe_eis_cq_thread8_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_EIS_CQ_THR_DONE_P2_9, "wpe_eis_cq_thread9_frame_done"},
	/*WPE_TNR frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_0, "wpe_tnr_cq_thread0_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_1, "wpe_tnr_cq_thread1_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_2, "wpe_tnr_cq_thread2_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_3, "wpe_tnr_cq_thread3_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_4, "wpe_tnr_cq_thread4_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_5, "wpe_tnr_cq_thread5_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_6, "wpe_tnr_cq_thread6_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_7, "wpe_tnr_cq_thread7_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_8, "wpe_tnr_cq_thread8_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_TNR_CQ_THR_DONE_P2_9, "wpe_tnr_cq_thread9_frame_done"},
	/*WPE_LITE frame done*/
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_0, "wpe_lite_cq_thread0_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_1, "wpe_lite_cq_thread1_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_2, "wpe_lite_cq_thread2_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_3, "wpe_lite_cq_thread3_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_4, "wpe_lite_cq_thread4_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_5, "wpe_lite_cq_thread5_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_6, "wpe_lite_cq_thread6_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_7, "wpe_lite_cq_thread7_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_8, "wpe_lite_cq_thread8_frame_done"},
	{IMGSYS_CMDQ_EVENT_IMG_WPE_LITE_CQ_THR_DONE_P2_9, "wpe_lite_cq_thread9_frame_done"},
	/*ME done*/
	{IMGSYS_CMDQ_EVENT_IMG_IMGSYS_IPE_ME_DONE, "me_done"},
	/*ADL done*/
	{IMGSYS_CMDQ_EVENT_IMG_ADL_TILE_DONE_EVENT, "adl_tile_done"},
	/* SW event */
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_WPE_EIS, "wpe_eis_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_WPE_TNR, "wpe_tnr_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_WPE_LITE, "wpe_lite_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_TRAW, "traw_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_LTRAW, "ltraw_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_XTRAW, "xtraw_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_DIP, "dip_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_PQDIP_A, "pqdip_a_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_PQDIP_B, "pqdip_b_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IPESYS_ME, "me_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_APUSYS_APU, "apu_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_TRAW, "vss_traw_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_LTRAW, "vss_ltraw_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_XTRAW, "vss_xtraw_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_VSS_DIP, "vss_dip_sync_token"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_1, "sw_sync_token_pool_1"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_2, "sw_sync_token_pool_2"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_3, "sw_sync_token_pool_3"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_4, "sw_sync_token_pool_4"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_5, "sw_sync_token_pool_5"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_6, "sw_sync_token_pool_6"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_7, "sw_sync_token_pool_7"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_8, "sw_sync_token_pool_8"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_9, "sw_sync_token_pool_9"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_10, "sw_sync_token_pool_10"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_11, "sw_sync_token_pool_11"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_12, "sw_sync_token_pool_12"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_13, "sw_sync_token_pool_13"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_14, "sw_sync_token_pool_14"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_15, "sw_sync_token_pool_15"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_16, "sw_sync_token_pool_16"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_17, "sw_sync_token_pool_17"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_18, "sw_sync_token_pool_18"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_19, "sw_sync_token_pool_19"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_20, "sw_sync_token_pool_20"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_21, "sw_sync_token_pool_21"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_22, "sw_sync_token_pool_22"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_23, "sw_sync_token_pool_23"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_24, "sw_sync_token_pool_24"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_25, "sw_sync_token_pool_25"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_26, "sw_sync_token_pool_26"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_27, "sw_sync_token_pool_27"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_28, "sw_sync_token_pool_28"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_29, "sw_sync_token_pool_29"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_30, "sw_sync_token_pool_30"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_31, "sw_sync_token_pool_31"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_32, "sw_sync_token_pool_32"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_33, "sw_sync_token_pool_33"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_34, "sw_sync_token_pool_34"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_35, "sw_sync_token_pool_35"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_36, "sw_sync_token_pool_36"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_37, "sw_sync_token_pool_37"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_38, "sw_sync_token_pool_38"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_39, "sw_sync_token_pool_39"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_40, "sw_sync_token_pool_40"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_41, "sw_sync_token_pool_41"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_42, "sw_sync_token_pool_42"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_43, "sw_sync_token_pool_43"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_44, "sw_sync_token_pool_44"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_45, "sw_sync_token_pool_45"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_46, "sw_sync_token_pool_46"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_47, "sw_sync_token_pool_47"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_48, "sw_sync_token_pool_48"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_49, "sw_sync_token_pool_49"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_50, "sw_sync_token_pool_50"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_51, "sw_sync_token_pool_51"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_52, "sw_sync_token_pool_52"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_53, "sw_sync_token_pool_53"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_54, "sw_sync_token_pool_54"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_55, "sw_sync_token_pool_55"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_56, "sw_sync_token_pool_56"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_57, "sw_sync_token_pool_57"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_58, "sw_sync_token_pool_58"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_59, "sw_sync_token_pool_59"},
	{IMGSYS_CMDQ_SYNC_TOKEN_IMGSYS_POOL_60, "sw_sync_token_pool_60"},

	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_1, "sw_sync_token_camsys_pool_1"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_2, "sw_sync_token_camsys_pool_2"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_3, "sw_sync_token_camsys_pool_3"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_4, "sw_sync_token_camsys_pool_4"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_5, "sw_sync_token_camsys_pool_5"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_6, "sw_sync_token_camsys_pool_6"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_7, "sw_sync_token_camsys_pool_7"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_8, "sw_sync_token_camsys_pool_8"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_9, "sw_sync_token_camsys_pool_9"},
	{IMGSYS_CMDQ_SYNC_TOKEN_CAMSYS_POOL_10, "sw_sync_token_camsys_pool_10"},
	{IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ISP_WAIT, "sw_sync_token_tzmp_isp_wait"},
	{IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ISP_SET, "sw_sync_token_tzmp_isp_set"},
	{IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ADL_WAIT, "sw_sync_token_tzmp_adl_wait"},
	{IMGSYS_CMDQ_SYNC_TOKEN_TZMP_ADL_SET, "sw_sync_token_tzmp_adl_set"},
	{IMGSYS_CMDQ_EVENT_MAX, "imgsys_event_max"},
};

struct block_record {
	u32            label_min;
	u32            label_max;
	u32            label_count;
	u32            cmd_offset;
	u32            cmd_length;
};

enum GCE_REC_BLOCK_ENUM {
	GCE_REC_NONE_BLOCK = -1,
	GCE_REC_FRAME_BLOCK = 0,
	GCE_REC_TILE_BLOCK
};

enum GCE_REC_MODE_ENUM {
	GCE_REC_APPEND_MODE = 0,
	GCE_REC_REPLACE_MODE
};

struct gce_recorder {
	u32            header_code;
	u32            cmd_offset;
	u32            check_pre;
	u32            *p_output;
	u32            check_post;
	u32            *p_buffer;
	u32            max_length;
	u32            curr_length;

	struct block_record  frame_record[GCE_REC_MAX_FRAME_BLOCK];
	u32            frame_block;
	u32            curr_frame;

	struct block_record  tile_record[GCE_REC_MAX_TILE_BLOCK];
	u32            tile_block;
	u32            curr_tile;

	enum GCE_REC_BLOCK_ENUM  curr_block;
	enum GCE_REC_MODE_ENUM   curr_mode;

	u32            orig_index;
	u32            *p_orig_out;
	u32            curr_label;

	enum GCE_REC_BLOCK_ENUM  label_block;

	u32            frame_label[GCE_REC_MAX_LABEL_COUNT];
	u32            frame_count;

	u32            tile_label[GCE_REC_MAX_LABEL_COUNT];
	u32            tile_count;

	u32            footer_code;
};

struct smi_port_t {
	u32 portenum;
	u32 portbw;
} __packed;

struct wpe_bw_t {
	u32 totalbw;
	struct smi_port_t smiport[WPE_SMI_PORT_NUM];
} __packed;

struct me_bw_t {
	u32 totalbw;
	struct smi_port_t smiport[ME_SMI_PORT_NUM];
} __packed;

struct pqdip_bw_t {
	u32 totalbw;
	struct smi_port_t smiport[PQ_DIP_SMI_PORT_NUM];
} __packed;

struct traw_bw_t {
	u32 totalbw;
	struct smi_port_t smiport[TRAW_SMI_PORT_NUM];
} __packed;

struct ltraw_bw_t {
	u32 totalbw;
	struct smi_port_t smiport[LTRAW_SMI_PORT_NUM];
} __packed;

struct xtraw_bw_t {
	u32 totalbw;
	struct smi_port_t smiport[XTRAW_SMI_PORT_NUM];
} __packed;

struct dip_bw_t {
	u32 totalbw;
	struct smi_port_t smiport[DIP_SMI_PORT_NUM];
} __packed;

struct adl_bw_t {
	u32 totalbw;
	struct smi_port_t smiport[ADL_SMI_PORT_NUM];
} __packed;

struct frame_bw_t {
	struct wpe_bw_t wpe_eis;
	struct wpe_bw_t wpe_tnr;
	struct wpe_bw_t wpe_lite;
	struct me_bw_t me;
	struct pqdip_bw_t pqdip_a;
	struct pqdip_bw_t pqdip_b;
	struct traw_bw_t traw;
	struct ltraw_bw_t ltraw;
	struct xtraw_bw_t xtraw;
	struct dip_bw_t dip;
	struct adl_bw_t ad;
} __packed;

#endif /* _MTK_IMGSYS_CMDQ_PLAT_H_ */

