/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019 MediaTek Inc.
 */

#ifndef _KD_IMGSENSOR_DATA_V4L2_H
#define _KD_IMGSENSOR_DATA_V4L2_H

enum VC_FEATURE {
	VC_NONE = 0,
	VC_MIN_NUM,
	VC_RAW_DATA = VC_MIN_NUM,
	VC_RAW_DATA_MAX,

	VC_PDAF_MIN_NUM = VC_RAW_DATA_MAX,
	VC_PDAF_STATS = VC_PDAF_MIN_NUM,
	VC_PDAF_STATS_NE,
	VC_PDAF_STATS_ME,
	VC_PDAF_STATS_SE,
	VC_PDAF_STATS_PIX_1,
	VC_PDAF_STATS_PIX_2,
	VC_PDAF_STATS_NE_PIX_1 = VC_PDAF_STATS_PIX_1,
	VC_PDAF_STATS_NE_PIX_2 = VC_PDAF_STATS_PIX_2,
	VC_PDAF_STATS_ME_PIX_1,
	VC_PDAF_STATS_ME_PIX_2,
	VC_PDAF_STATS_SE_PIX_1,
	VC_PDAF_STATS_SE_PIX_2,
	VC_PDAF_MAX_NUM,

	VC_HDR_MIN_NUM = VC_PDAF_MAX_NUM,
	VC_HDR_MVHDR = VC_HDR_MIN_NUM,
	VC_HDR_MAX_NUM,

	VC_3HDR_MIN_NUM = VC_HDR_MAX_NUM,
	VC_3HDR_EMBEDDED = VC_3HDR_MIN_NUM,
	VC_3HDR_FLICKER,
	VC_3HDR_Y,
	VC_3HDR_AE,
	VC_3HDR_MAX_NUM,

	VC_STAGGER_MIN_NUM = VC_3HDR_MAX_NUM,
	VC_STAGGER_EMBEDDED = VC_STAGGER_MIN_NUM,
	VC_STAGGER_NE,
	VC_STAGGER_ME,
	VC_STAGGER_SE,
	VC_STAGGER_MAX_NUM,

	VC_YUV_MIN_NUM = VC_STAGGER_MAX_NUM,
	VC_YUV_Y = VC_YUV_MIN_NUM,
	VC_YUV_UV,
	VC_YUV_MAX_NUM,

	VC_RAW_EXT_MIN_NUM = VC_YUV_MAX_NUM,
	VC_RAW_W_DATA = VC_RAW_EXT_MIN_NUM,
	VC_RAW_PROCESSED_DATA,
	VC_RAW_EXT_MAX_NUM,

	VC_GENERAL_DATA_MIN_NUM = VC_RAW_EXT_MAX_NUM,
	VC_GENERAL_EMBEDDED = VC_GENERAL_DATA_MIN_NUM,
	VC_GENERAL_DATA_MAX_NUM,

	VC_MAX_NUM = VC_GENERAL_DATA_MAX_NUM,
};

enum {
	PAD_SINK = 0,
	PAD_SRC_RAW0,
	PAD_SRC_RAW1,
	PAD_SRC_RAW2,
	PAD_SRC_RAW_W0,
	PAD_SRC_RAW_EXT0,
	PAD_SRC_PDAF0,
	PAD_SRC_PDAF1,
	PAD_SRC_PDAF2,
	PAD_SRC_PDAF3,
	PAD_SRC_PDAF4,
	PAD_SRC_PDAF5,
	PAD_SRC_PDAF6,
	PAD_SRC_HDR0,
	PAD_SRC_HDR1,
	PAD_SRC_HDR2,
	PAD_SRC_GENERAL0,
	PAD_MAXCNT,
	PAD_ERR = 0xffff,
};

#endif              /* _KD_IMGSENSOR_DATA_H */
