/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2023 MediaTek Inc.
 */

#ifndef __APUSYS_SECURE_H__
#define __APUSYS_SECURE_H__

enum mtk_apusys_kernel_op {
	MTK_APUSYS_KERNEL_OP_APUSYS_PWR_TOP_ON,		/*  0 */
	MTK_APUSYS_KERNEL_OP_APUSYS_PWR_TOP_OFF,	/*  1 */
	MTK_APUSYS_KERNEL_OP_APUSYS_RV_SETUP_REVISER,	/*  2 */
	MTK_APUSYS_KERNEL_OP_APUSYS_RV_RESET_MP,	/*  3 */
	MTK_APUSYS_KERNEL_OP_APUSYS_RV_SETUP_BOOT,	/*  4 */
	MTK_APUSYS_KERNEL_OP_APUSYS_RV_START_MP,	/*  5 */
	MTK_APUSYS_KERNEL_OP_APUSYS_RV_STOP_MP,		/*  6 */
	MTK_APUSYS_KERNEL_OP_DEVAPC_INIT_RCX,		/*  7 */
	MTK_APUSYS_KERNEL_OP_APUSYS_RV_SETUP_SEC_MEM,	/*  8 */
	MTK_APUSYS_KERNEL_OP_APUSYS_RV_DISABLE_WDT_ISR,	/*  9 */
	MTK_APUSYS_KERNEL_OP_APUSYS_RV_CLEAR_WDT_ISR,	/* 10 */
	MTK_APUSYS_KERNEL_OP_APUSYS_RV_CG_GATING,	/* 11 */
	MTK_APUSYS_KERNEL_OP_APUSYS_RV_CG_UNGATING,	/* 12 */
	MTK_APUSYS_KERNEL_OP_NUM,
};

#endif
