/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018 MediaTek Inc.
 *
 * Author: Frederic Chen <frederic.chen@mediatek.com>
 *
 */

#ifndef _MTK_ME_V4L2_VNODE_H_
#define _MTK_ME_V4L2_VNODE_H_

#include "../mtk_imgsys-dev.h"
#include "../mtk_imgsys-formats.h"
#include "../mtk_imgsys-vnode_id.h"

static const struct mtk_imgsys_dev_format me_fmts[] = {
	{
		.fmt = &mtk_imgsys_format_y32,
		.align = 1,
		.scan_align = 1,
	},
	{
		.fmt = &mtk_imgsys_format_y16,
		.align = 1,
		.scan_align = 1,
	},
	{
		.fmt = &mtk_imgsys_format_y8,
		.align = 1,
		.scan_align = 1,
	},
	{
		.fmt = &mtk_imgsys_format_grey,
		.align = 16,
		.scan_align = 1,
	},
};

static const struct mtk_imgsys_dev_format mewmap_fmts[] = {
	{
		.fmt = &mtk_imgsys_format_warp2p,
		.align = 1168,
		.scan_align = 217,
	},
};

static const struct mtk_imgsys_dev_format melmi_fmts[] = {
	{
		.fmt = &mtk_imgsys_format_y16,
		.align = 1,
		.scan_align = 1,
	},
};

/* TODO: Replace with a different format */
static const struct mtk_imgsys_dev_format mel1i_fmts[] = {
	{
		.fmt = &mtk_imgsys_format_grey,
		.align = 576,
		.scan_align = 432,
	},
};

static const struct v4l2_frmsizeenum in_frmsizeenum = {
	.type = V4L2_FRMSIZE_TYPE_CONTINUOUS,
	.stepwise.max_width = MTK_DIP_CAPTURE_MAX_WIDTH,
	.stepwise.min_width = MTK_DIP_CAPTURE_MIN_WIDTH,
	.stepwise.max_height = MTK_DIP_CAPTURE_MAX_HEIGHT,
	.stepwise.min_height = MTK_DIP_CAPTURE_MIN_HEIGHT,
	.stepwise.step_height = 1,
	.stepwise.step_width = 1,
};

static const struct v4l2_frmsizeenum out_frmsizeenum = {
	.type = V4L2_FRMSIZE_TYPE_CONTINUOUS,
	.stepwise.max_width = MTK_DIP_OUTPUT_MAX_WIDTH,
	.stepwise.min_width = MTK_DIP_OUTPUT_MIN_WIDTH,
	.stepwise.max_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
	.stepwise.min_height = MTK_DIP_OUTPUT_MIN_HEIGHT,
	.stepwise.step_height = 1,
	.stepwise.step_width = 1,
};

static const struct mtk_imgsys_video_device_desc me_setting[] = {
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL0IMG0_OUT,
		.name = "L0I0I Input",
		.cap = V4L2_CAP_VIDEO_OUTPUT_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &in_frmsizeenum,
		.description = "ME Input",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL0IMG1_OUT,
		.name = "L0I1I Input",
		.cap = V4L2_CAP_VIDEO_OUTPUT_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &in_frmsizeenum,
		.description = "ME Input",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL1IMG0_OUT,
		.name = "L1I0I Input",
		.cap = V4L2_CAP_VIDEO_OUTPUT_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = mel1i_fmts,
		.num_fmts = ARRAY_SIZE(mel1i_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &in_frmsizeenum,
		.description = "ME L1 Input ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL1IMG1_OUT,
		.name = "L1I1I Input",
		.cap = V4L2_CAP_VIDEO_OUTPUT_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = mel1i_fmts,
		.num_fmts = ARRAY_SIZE(mel1i_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &in_frmsizeenum,
		.description = "ME L1 Input ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEIMGSTATS_OUT,
		.name = "STATI Input",
		.cap = V4L2_CAP_VIDEO_OUTPUT_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &in_frmsizeenum,
		.description = "ME IMGSTATS Input ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL0RMV_OUT,
		.name = "L0RMVI Input",
		.cap = V4L2_CAP_VIDEO_OUTPUT_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &in_frmsizeenum,
		.description = "ME L0RMV Input ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL1RMV_OUT,
		.name = "L1RMVI Input",
		.cap = V4L2_CAP_VIDEO_OUTPUT_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &in_frmsizeenum,
		.description = "ME L1RMV Input ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL0FMB_OUT,
		.name = "L0FMBI Input",
		.cap = V4L2_CAP_VIDEO_OUTPUT_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &in_frmsizeenum,
		.description = "ME L0FMB Input ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL1FMB_OUT,
		.name = "L1FMBI Input",
		.cap = V4L2_CAP_VIDEO_OUTPUT_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &in_frmsizeenum,
		.description = "ME L1FMB Input ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEMIL_OUT,
		.name = "MEMILI Input",
		.cap = V4L2_CAP_VIDEO_OUTPUT_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_OUTPUT_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &in_frmsizeenum,
		.description = "ME MIL Input ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEMMGMIL_CAPTURE,
		.name = "MILO Output",
		.cap = V4L2_CAP_VIDEO_CAPTURE_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &out_frmsizeenum,
		.description = "ME MMGMIL Output ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL0WMV_CAPTURE,
		.name = "L0WMVO Output",
		.cap = V4L2_CAP_VIDEO_CAPTURE_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &out_frmsizeenum,
		.description = "ME L0WMV Output ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL1WMV_CAPTURE,
		.name = "L1WMVO Output",
		.cap = V4L2_CAP_VIDEO_CAPTURE_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &out_frmsizeenum,
		.description = "ME L1WMV Output ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MECONF_CAPTURE,
		.name = "CONFO Output",
		.cap = V4L2_CAP_VIDEO_CAPTURE_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &out_frmsizeenum,
		.description = "ME CONF Output ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEWMAP_CAPTURE,
		.name = "WMAPO Output",
		.cap = V4L2_CAP_VIDEO_CAPTURE_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = mewmap_fmts,
		.num_fmts = ARRAY_SIZE(mewmap_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &out_frmsizeenum,
		.description = "ME WMAP Output ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEFMV_CAPTURE,
		.name = "FMVO Output",
		.cap = V4L2_CAP_VIDEO_CAPTURE_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &out_frmsizeenum,
		.description = "ME OTHERS Output ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEFST_CAPTURE,
		.name = "FSTO Output",
		.cap = V4L2_CAP_VIDEO_CAPTURE_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &out_frmsizeenum,
		.description = "ME FST Output ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MELMI_CAPTURE,
		.name = "LMIO Output",
		.cap = V4L2_CAP_VIDEO_CAPTURE_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = melmi_fmts,
		.num_fmts = ARRAY_SIZE(melmi_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &out_frmsizeenum,
		.description = "ME LMI Output ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL0WFMB_CAPTURE,
		.name = "L0FMBO Output",
		.cap = V4L2_CAP_VIDEO_CAPTURE_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &out_frmsizeenum,
		.description = "ME L0FMB Output ",
	},
	{
		.id = MTK_IMGSYS_VIDEO_NODE_ID_MEL1WFMB_CAPTURE,
		.name = "L1FMBO Output",
		.cap = V4L2_CAP_VIDEO_CAPTURE_MPLANE | V4L2_CAP_STREAMING,
		.buf_type = V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE,
		.smem_alloc = 0,
		.supports_ctrls = true,
		.flags = MEDIA_LNK_FL_DYNAMIC,
		.fmts = me_fmts,
		.num_fmts = ARRAY_SIZE(me_fmts),
		.default_width = MTK_DIP_OUTPUT_MAX_WIDTH,
		.default_height = MTK_DIP_OUTPUT_MAX_HEIGHT,
		.frmsizeenum = &out_frmsizeenum,
		.description = "ME L1FMB Output ",
	},
};

#endif /* _MTK_ME_V4L2_VNODE_H_ */
